# Generated by Django 2.2 on 2020-10-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='link',
        ),
    ]
